"""
Recursive density estimation under real–synthetic mixing (biased-real stream; KDE/ECDF option).

This script runs a recursive estimator over T outer iterations. At each iteration n:

  (1) Draw m1 NEW real samples from a *biased* distribution P_n.
      - The unbiased target distribution P0 is a 2-component Gaussian mixture.
      - The biased real stream P_n adds an extra (3rd) Gaussian component with
        time-decaying mixing weight bias_n.

  (2) Draw m2 synthetic samples from the *current* estimator and append them to
      the synthetic pool (memory).

  (3) Recompute the estimator from the accumulated dataset:
          X_train = (all past real) ∪ (all past synthetic).

Estimator modes:
  • KDE mode (default): Gaussian kernel density estimate on a fixed grid with
    bandwidth schedule h_n = h0 * n^(-p_target/2).
    Synthetic samples are generated by: pick a random training point and add
    N(0, h_n^2) noise (i.e., sampling from the KDE).

  • ECDF mode (optional): empirical CDF on the grid, numerically differentiated
    to produce a density for density-based metrics; synthetic samples are drawn
    by resampling from the current empirical distribution (no kernel noise).

Metrics (evaluated against the unbiased target P0 on a fixed grid):
  • Wasserstein-1 distance (W1): computed as ∫ |F_true(x) - F_hat(x)| dx
    using trapezoidal integration on the grid.
  • MMD^2 (Gaussian kernel): computed via grid quadrature using a precomputed
    kernel matrix K over the grid points.

Notes for publication:
  • The “bias” affects ONLY the real-sample stream (the data you observe).
    All metrics are computed w.r.t. the unbiased target P0.
  • Experimental parameters (T, m1, alpha grid, bias-rate grid, bandwidth schedule,
    logging/plotting cadence, etc.) are unchanged from your provided code.
  • Total variation (TV) has been removed entirely (computation, storage, plots,
    slopes, and summaries).

Outputs:
  • Per-condition density plot for the first replicate (final iteration).
  • Trend plots (log10 metric vs log10 M_n) for W1 and MMD^2 on the last replicate.
  • summary_table.csv: theoretical rate vs observed W1 rate (mean/median over reps).
  • all_results.json: raw arrays and per-replicate slopes (W1, MMD^2).

Windows/Jupyter safety:
  • Uses a timestamp without ':' for folder names.
  • No multiprocessing; deterministic structure is unchanged.
"""

import os, json, csv, datetime, logging
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

from scipy.stats import norm
from scipy.special import ndtr
from sklearn.linear_model import LinearRegression

import torch


# ============================================================
# 1. Unbiased target (2-Gaussian mixture) + biased sampler (3rd component)
# ============================================================
w1 = 0.35
mu1, sigma1 = -2.0, 0.8
mu2, sigma2 =  1.0, 1.3

# Biased extra component (edit only if your paper specifies different params)
mu3, sigma3 = 3.0, 1.0


def sample_true_np(n, rng, bias=0.0):
    """NumPy sampler for the biased real stream: P_n = (1-bias)*P0 + bias*N(mu3,sigma3^2)."""
    if n <= 0:
        return np.empty(0, float)
    bias = float(np.clip(bias, 0.0, 1.0))

    u = rng.random(n)
    m3 = u < bias

    u2 = rng.random(n)
    m1_mask = (~m3) & (u2 < w1)

    n3 = int(m3.sum())
    n1 = int(m1_mask.sum())
    n2 = n - n1 - n3

    x = np.empty(n, float)
    i = 0
    if n3:
        x[i:i+n3] = rng.normal(mu3, sigma3, n3)
        i += n3
    if n1:
        x[i:i+n1] = rng.normal(mu1, sigma1, n1)
        i += n1
    if n2:
        x[i:i+n2] = rng.normal(mu2, sigma2, n2)
    return x


def true_pdf_np(x):
    """Unbiased target density f0(x): 2-Gaussian mixture."""
    return w1 * norm.pdf(x, mu1, sigma1) + (1 - w1) * norm.pdf(x, mu2, sigma2)


def true_cdf_np(x):
    """Unbiased target CDF F0(x): 2-Gaussian mixture."""
    return w1 * ndtr((x - mu1) / sigma1) + (1 - w1) * ndtr((x - mu2) / sigma2)


def true_pdf_torch(x_t):
    """Torch version of the unbiased target density f0(x)."""
    c1 = w1 / (sigma1 * np.sqrt(2 * np.pi))
    c2 = (1 - w1) / (sigma2 * np.sqrt(2 * np.pi))
    z1 = (x_t - mu1) / sigma1
    z2 = (x_t - mu2) / sigma2
    return c1 * torch.exp(-0.5 * z1**2) + c2 * torch.exp(-0.5 * z2**2)


def true_cdf_torch(x_t):
    """Torch version of the unbiased target CDF F0(x)."""
    z1 = (x_t - mu1) / sigma1
    z2 = (x_t - mu2) / sigma2
    Phi1 = 0.5 * (1 + torch.erf(z1 / np.sqrt(2.0)))
    Phi2 = 0.5 * (1 + torch.erf(z2 / np.sqrt(2.0)))
    return w1 * Phi1 + (1 - w1) * Phi2


def sample_true_torch(n, device, dtype=torch.float64, bias=0.0):
    """Torch sampler for biased real stream."""
    if n <= 0:
        return torch.empty(0, device=device, dtype=dtype)
    bias = float(np.clip(bias, 0.0, 1.0))

    u = torch.rand(n, device=device, dtype=dtype)
    m3 = u < bias

    u2 = torch.rand(n, device=device, dtype=dtype)
    m1_mask = (~m3) & (u2 < w1)

    n3 = int(m3.sum().item())
    n1 = int(m1_mask.sum().item())
    n2 = n - n1 - n3

    xs = []
    if n3:
        xs.append(torch.randn(n3, device=device, dtype=dtype) * sigma3 + mu3)
    if n1:
        xs.append(torch.randn(n1, device=device, dtype=dtype) * sigma1 + mu1)
    if n2:
        xs.append(torch.randn(n2, device=device, dtype=dtype) * sigma2 + mu2)

    return torch.cat(xs, dim=0) if xs else torch.empty(0, device=device, dtype=dtype)


# Fixed grid for deterministic metric computation against the unbiased target
left = min(mu1 - 6 * sigma1, mu2 - 6 * sigma2)
right = max(mu1 + 6 * sigma1, mu2 + 6 * sigma2)
m_grid = 500

xg = np.linspace(left, right, m_grid)
dx = xg[1] - xg[0]
F_true_g = true_cdf_np(xg)
f_true_g = true_pdf_np(xg)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DTYPE = torch.float64

xg_t = torch.from_numpy(xg).to(device=DEVICE, dtype=DTYPE)
dx_t = xg_t[1] - xg_t[0]

F_true_g_t = torch.from_numpy(F_true_g).to(device=DEVICE, dtype=DTYPE)
f_true_g_t = torch.from_numpy(f_true_g).to(device=DEVICE, dtype=DTYPE)

# Precompute Gaussian-kernel matrix for MMD^2 quadrature on the grid
MMD_SIGMA = 0.5
Xgrid = xg_t.view(-1, 1)
K_mmd = torch.exp(-(Xgrid - Xgrid.T) ** 2 / (2.0 * MMD_SIGMA**2))


# ============================================================
# 2. Helper routines (torch, grid-based)
# ============================================================
def silverman_bw_np(x):
    """Silverman's rule-of-thumb (not used in current experiment; kept for reference)."""
    s = np.std(x, ddof=1)
    n = len(x)
    if n <= 1 or s == 0:
        return 1.0
    return 1.06 * s * n ** (-1 / 5)


def cdf_from_pdf_on_grid_torch(pdf_vals, dx, renormalize=True):
    """Numerically integrate a grid density to obtain a CDF on the same grid."""
    F = torch.empty_like(pdf_vals)
    F[0] = 0.0
    F[1:] = torch.cumsum((pdf_vals[:-1] + pdf_vals[1:]) * 0.5 * dx, dim=0)
    if renormalize:
        total = F[-1].clamp_min(1e-12)
        F = F / total
    return F


def w1_from_cdfs_on_grid_torch(F_true, F_model, xg_t):
    """W1 distance in 1D via integral of CDF difference: ∫ |F_true - F_model| dx."""
    return torch.trapz(torch.abs(F_true - F_model), xg_t)


def empirical_cdf_on_grid_torch(samples, xg_t):
    """Compute ECDF values F_hat(xg) on the grid xg_t."""
    s, _ = torch.sort(samples)
    n = s.shape[0]
    idx = torch.searchsorted(s, xg_t, right=True)
    return idx.to(dtype=DTYPE) / float(n)


def mmd2_from_pdfs_torch(f_true, f_model, K, dx):
    """
    MMD^2 between two densities represented on a grid:
      MMD^2 = ∬ k(x,y) (f_true(x)-f_model(x)) (f_true(y)-f_model(y)) dx dy

    With grid quadrature:
      MMD^2 ≈ (f_true^T K f_true + f_model^T K f_model - 2 f_true^T K f_model) * dx^2
    """
    v_true = torch.mv(K, f_true)
    v_model = torch.mv(K, f_model)
    dx2 = dx * dx
    return (torch.dot(f_true, v_true) + torch.dot(f_model, v_model) - 2.0 * torch.dot(f_true, v_model)) * dx2


# ============================================================
# 3. Recursive estimator (biased real stream; unbiased target for metrics)
# ============================================================
def run_recursive_estimator(
    p_target=0.5,
    alpha=0.5,
    m1=50,
    T=200,
    use_ecdf=False,
    h0=0.5,
    bias_rate=0.0
):
    """
    Run T-step recursion. Real stream is biased; metrics are computed vs. unbiased target.

    Parameters are unchanged:
      - p_target controls bandwidth decay exponent in KDE mode: h_n = h0 * n^(-p_target/2)
      - alpha controls the synthetic fraction via m2 = round(alpha*m1/(1-alpha)) (as before)
      - bias_rate=q sets bias_n = 0.2*(n+5)^(-q) when q>0, else 0
    """
    device, dtype = DEVICE, DTYPE

    # Synthetic batch size per step is fixed from alpha and m1 (unchanged)
    m2 = 0 if alpha <= 0 else int(round(alpha * m1 / (1 - alpha)))
    alpha_used = m2 / (m1 + m2) if (m1 + m2) > 0 else 0.0

    X_real = torch.empty(0, device=device, dtype=dtype)
    X_synth = torch.empty(0, device=device, dtype=dtype)

    Ms = np.empty(T, int)
    W1s = np.empty(T, float)
    MMD2s = np.empty(T, float)
    bandwidths = np.empty(T, float)

    f_hat_history = []
    F_hat_history = []

    h0_ = None
    M1 = None
    normal_const = 1.0 / np.sqrt(2.0 * np.pi)

    with torch.no_grad():
        for n in range(1, T + 1):
            idx = n - 1

            # Bias schedule for the real stream (unchanged)
            bias = (0.2) * (n + 5) ** (-bias_rate) if bias_rate > 0 else 0.0

            # (1) Add new real samples
            x_new_real = sample_true_torch(m1, device=device, dtype=dtype, bias=bias)
            X_real = torch.cat((X_real, x_new_real), dim=0)

            # Training set is accumulated real + accumulated synthetic
            X_train = torch.cat((X_real, X_synth), dim=0) if X_synth.numel() > 0 else X_real
            M_n = X_train.shape[0]
            Ms[idx] = int(M_n)

            if use_ecdf:
                # ECDF on grid; differentiate numerically for density-based metrics
                F_hat_g_t = empirical_cdf_on_grid_torch(X_train, xg_t)
                dx_vec = torch.full_like(F_hat_g_t, dx_t)
                f_hat_g_t = torch.gradient(F_hat_g_t, spacing=(dx_vec,))[0]
                bandwidths[idx] = 0.0

                # Synthetic sampling in ECDF mode: resample from empirical distribution
                if m2 > 0:
                    ir = torch.randint(0, M_n, (m2,), device=device)
                    X_synth = torch.cat((X_synth, X_train[ir]), dim=0)

            else:
                # KDE bandwidth schedule (unchanged)
                if h0_ is None:
                    h0_ = h0 if h0 > 0 else 0.5
                    M1 = float(M_n)

                h_n = h0_ * (n) ** (-p_target / 2.0)
                bandwidths[idx] = float(h_n)

                h_n_t = torch.tensor(h_n, device=device, dtype=dtype)

                # KDE on the fixed grid
                diff = (xg_t.unsqueeze(1) - X_train.unsqueeze(0)) / h_n_t
                f_hat_g_t = torch.exp(-0.5 * diff**2).mean(dim=1) * (normal_const / h_n_t)
                F_hat_g_t = cdf_from_pdf_on_grid_torch(f_hat_g_t, dx_t, True)

                # Synthetic sampling from KDE: pick a training point + Gaussian noise
                if m2 > 0:
                    ir = torch.randint(0, M_n, (m2,), device=device)
                    synth = X_train[ir] + torch.randn(m2, device=device, dtype=dtype) * h_n_t
                    X_synth = torch.cat((X_synth, synth), dim=0)

            # Metrics vs unbiased target (TV removed; W1 and MMD^2 retained)
            W1s[idx] = float(w1_from_cdfs_on_grid_torch(F_true_g_t, F_hat_g_t, xg_t).cpu().item())
            MMD2s[idx] = float(mmd2_from_pdfs_torch(f_true_g_t, f_hat_g_t, K_mmd, float(dx)).cpu().item())

            # Optional history for diagnostics/plots
            f_hat_history.append(f_hat_g_t.cpu().numpy())
            F_hat_history.append(F_hat_g_t.cpu().numpy())

            if (n == 1) or (n % 50 == 0):
                tag = "ECDF" if use_ecdf else "KDE"
                hn = 0.0 if use_ecdf else h_n
                print(
                    f"[{tag} p={p_target:.2f}, alpha≈{alpha_used:.2f}, q={bias_rate:.2f}] "
                    f"n={n:4d} M={M_n:6d} bias={bias:.4g} h={hn:.4g} W1={W1s[idx]:.6f}"
                )

            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    return dict(
        M=Ms,
        W1=W1s,
        MMD2=MMD2s,
        bandwidths=bandwidths,
        p_target=p_target,
        alpha=alpha_used,
        m1=m1,
        m2=m2,
        use_ecdf=use_ecdf,
        f_hat_history=np.stack(f_hat_history),
        F_hat_history=np.stack(F_hat_history),
        bias_rate=bias_rate,
    )


# ============================================================
# 4. Power-law slope estimators + JSON helper (unchanged logic; TV removed)
# ============================================================
def estimate_power_law_slope(M, vals, drop_first=10):
    """
    Fit log(vals) ≈ a + b log(M) on the tail (drop_first ... end).
    Returns (b, a). In plots we often report observed rate as -b.
    """
    M = np.asarray(M)
    vals = np.asarray(vals)
    if drop_first >= len(M) - 5:
        drop_first = max(0, len(M) - 5)
    Mu = M[drop_first:]
    Vu = vals[drop_first:]
    reg = LinearRegression().fit(np.log(Mu).reshape(-1, 1), np.log(Vu))
    return reg.coef_[0], reg.intercept_


def estimate_power_law_with_loglog(M, vals, drop_first=10):
    """
    Optional extended model: log(vals) ≈ a + b log(M) + c log log(M).
    (Not used in the main loop; kept for parity with your code.)
    """
    M = np.asarray(M)
    vals = np.asarray(vals)
    if drop_first >= len(M) - 5:
        drop_first = max(0, len(M) - 5)
    Mu = M[drop_first:]
    Vu = vals[drop_first:]
    logM = np.log(Mu)
    mask = (Vu > 0) & (Mu > 1.0) & (logM > 0)
    if mask.sum() < 3:
        raise ValueError("Not enough valid points to fit log-log-log model.")
    Mu, Vu, logM = Mu[mask], Vu[mask], logM[mask]
    X = np.column_stack([logM, np.log(logM)])
    reg = LinearRegression().fit(X, np.log(Vu))
    b, c = reg.coef_
    a = reg.intercept_
    return b, c, a, reg


def _make_json_serializable(obj):
    import numpy as _np
    if isinstance(obj, _np.ndarray):
        return obj.tolist()
    if isinstance(obj, (_np.float32, _np.float64)):
        return float(obj)
    if isinstance(obj, (_np.int32, _np.int64)):
        return int(obj)
    return obj


# ---------------------------------------------------------------------
# Main script — biased case + summary table (mean+median) [Windows-safe]
#   (Experimental parameters/details unchanged; TV removed.)
# ---------------------------------------------------------------------
import sys

if __name__ == "__main__":
    # --- experiment grids (unchanged) ---
    p_values = [0.5]
    alphas = [0.25, 0.5, 0.75]          # alpha_real values
    bias_rates = [0.25, 0.5, 0.75]      # q values

    # --- core run settings (unchanged) ---
    T, m1, n_reps, h0, drop_first = 2000, 50, 20, 2, 1500
    USE_ERROR_BARS = False  # unused (kept to avoid changing structure)

    # Windows-safe timestamp: avoid ":" in folder/file names
    ts = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    run_name = f"biased_alphaReal_h0={h0}_T={T}_m1={m1}_nreps={n_reps}_{ts}"
    out_dir = Path("logs") / "KDE" / run_name
    fig_dir = out_dir / "figures"
    out_dir.mkdir(parents=True, exist_ok=True)
    fig_dir.mkdir(parents=True, exist_ok=True)

    log_file = out_dir / "run.log"
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[
            logging.FileHandler(log_file, mode="w", encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )
    log = logging.info
    all_results = []

    def plot_density_first_rep(f_true_g, f_hat_t, xg, p_val, alpha_real, bias_rate, save_path):
        """Save the final-step density (first replicate) vs. the true target density."""
        plt.figure(figsize=(7, 4))
        plt.plot(xg, f_true_g, linewidth=2, label="True density")
        plt.plot(xg, f_hat_t, linewidth=2, label="Estimated density")
        plt.xlabel("x")
        plt.ylabel("density")
        plt.title(f"Estimated density (final): p={p_val}, alpha_real={alpha_real:.2f}, q={bias_rate:.2f}")
        plt.grid(True, axis="y", ls="--", alpha=0.3)
        plt.legend()
        plt.tight_layout()
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
        plt.close()

    def plot_with_trend(M, values, metric_name, p_val, alpha_real_val, bias_rate, drop_first=10, save_path=None):
        """Plot log10(metric) vs log10(M_n) and overlay a tail linear fit slope."""
        eps = 1e-20
        log_M = np.log10(M)
        log_val = np.log10(values + eps)

        plt.figure(figsize=(6, 4))
        plt.plot(log_M, log_val, "o-", alpha=0.5, markersize=3, label=metric_name)

        if len(M) > drop_first + 5:
            x_fit = log_M[drop_first:]
            y_fit = log_val[drop_first:]
            slope, intercept = np.polyfit(x_fit, y_fit, 1)
            y_pred = slope * x_fit + intercept
            plt.plot(x_fit, y_pred, "r--", linewidth=2, label=f"Fit slope: {slope:.3f}")

        plt.xlabel("log10(M_n)")
        plt.ylabel(f"log10({metric_name})")
        plt.title(f"{metric_name} Scaling: p={p_val}, alpha_real={alpha_real_val:.2f}, q={bias_rate:.2f}")
        plt.legend()
        plt.grid(True, which="both", ls="--", alpha=0.3)
        plt.tight_layout()

        if save_path is not None:
            plt.savefig(save_path, dpi=150, bbox_inches="tight")
            plt.close()
        else:
            plt.show()

    for alpha_real in alphas:
        # IMPORTANT: alpha_est passed into run_recursive_estimator is the *synthetic* fraction,
        #            so alpha_est = 1 - alpha_real (unchanged).
        alpha_est = 1.0 - alpha_real

        for q in bias_rates:
            log("\n" + "#" * 80)
            log(f"=== alpha_real={alpha_real:.2f} (alpha_est={alpha_est:.2f}), q={q:.2f} ===")

            for p in p_values:
                log("\n" + "=" * 70)
                log(f"Running {n_reps}×: p={p}, alpha_real={alpha_real:.2f}, q={q:.2f}")

                slopes_W1 = []
                slopes_MMD2 = []
                last_out = None

                for rep in range(n_reps):
                    log(f"--- rep {rep+1}/{n_reps} ---")

                    out = run_recursive_estimator(
                        p_target=p,
                        alpha=alpha_est,
                        m1=m1,
                        T=T,
                        use_ecdf=False,   # unchanged (KDE mode)
                        h0=h0,
                        bias_rate=q,
                    )

                    M_vals = out["M"]
                    W1_vals = out["W1"]
                    MMD2s = out["MMD2"]

                    # Save a representative density plot for the first replicate only
                    if rep == 0 and "f_hat_history" in out:
                        f_hat_final = out["f_hat_history"][-1]
                        dens_path = fig_dir / f"density_firstRep_p={p:.2f}_alphaReal={alpha_real:.2f}_q={q:.2f}.png"
                        plot_density_first_rep(f_true_g, f_hat_final, xg, p, alpha_real, q, dens_path)
                        log(f"Saved density plot -> {dens_path}")

                    # Borderline correction (unchanged) applied per your prior logic:
                    #   If p == alpha_real, normalize by log factors for slope fitting.
                    if np.isclose(p, alpha_real, atol=1e-8):
                        logM = np.log(np.maximum(M_vals, 2.0))
                        W1_for_slope = W1_vals / logM
                        MMD2_for_slope = MMD2s / (logM**2)
                    else:
                        W1_for_slope = W1_vals
                        MMD2_for_slope = MMD2s

                    sW1, _ = estimate_power_law_slope(M_vals, W1_for_slope, drop_first=drop_first)
                    sM2, _ = estimate_power_law_slope(M_vals, MMD2_for_slope, drop_first=drop_first)

                    slopes_W1.append(sW1)
                    slopes_MMD2.append(sM2)

                    log(f"rep {rep+1}: slope_W1={sW1:.3f} slope_MMD2={sM2:.3f}")

                    last_out = out
                    if torch.cuda.is_available():
                        torch.cuda.empty_cache()

                slopes_W1 = np.array(slopes_W1)
                slopes_MMD2 = np.array(slopes_MMD2)

                mean_W1, std_W1 = slopes_W1.mean(), slopes_W1.std(ddof=1)
                mean_MMD2, std_MMD2 = slopes_MMD2.mean(), slopes_MMD2.std(ddof=1)

                # Kept from your code: report MMD slope as mean(MMD2)/2 just as a convenience
                mean_MMD, std_MMD = mean_MMD2 / 2.0, std_MMD2 / 2.0

                alpha_used = float(last_out["alpha"])      # synthetic fraction actually used (from rounding)
                alpha_real_used = 1.0 - alpha_used         # real fraction actually used
                theo = min(p, alpha_real_used, q)          # theory rate (unchanged formula)

                log(f"*** avg over {n_reps} ***")
                log(f"mean slope W1={mean_W1:.3f} (std={std_W1:.3f}) | observed rate≈{-mean_W1:.3f}")
                log(f"mean slope MMD={mean_MMD:.3f} (std={std_MMD:.3f}) | mean slope MMD2={mean_MMD2:.3f}")
                log(f"theory rate min(p,alpha_real,q)={theo:.3f}")

                run_label = f"p={p:.2f}_a={alpha_real_used:.2f}_q={q:.2f}"
                plot_with_trend(last_out["M"], last_out["W1"], "W1", p, alpha_real_used, q, drop_first,
                                fig_dir / f"{run_label}_W1.png")
                plot_with_trend(last_out["M"], last_out["MMD2"], "MMD^2", p, alpha_real_used, q, drop_first,
                                fig_dir / f"{run_label}_MMD2.png")

                all_results.append({
                    **last_out,
                    "p_target": p,
                    "alpha_real": float(alpha_real_used),
                    "alpha_est": float(alpha_used),
                    "bias_rate": float(q),
                    "slopes_W1": slopes_W1,
                    "slopes_MMD2": slopes_MMD2,
                    "mean_slope_W1": mean_W1,
                    "mean_slope_MMD": mean_MMD,
                    "mean_slope_MMD2": mean_MMD2,
                })

    # Summary table: W1 rates only (TV removed)
    keys = sorted(set((r["alpha_real"], r["bias_rate"], r["p_target"]) for r in all_results))
    summary = []
    for a, q, p in keys:
        grp = [r for r in all_results if r["alpha_real"] == a and r["bias_rate"] == q and r["p_target"] == p]
        slopes = np.concatenate([np.asarray(r["slopes_W1"]) for r in grp])
        obs_mean = float(-slopes.mean())
        obs_median = float(-np.median(slopes))
        theo = float(min(p, a, q))
        summary.append(dict(
            alpha_real=a,
            bias_rate=q,
            p_target=p,
            theoretical_rate=theo,
            observed_rate_mean=obs_mean,
            observed_rate_median=obs_median,
        ))

    print("\nSUMMARY (W1 rates): observed rate = -slope")
    print(f"{'alpha':>6} {'q':>6} {'p':>5} {'theory':>10} {'obs_mean':>10} {'obs_med':>10}")
    for s in summary:
        print(
            f"{s['alpha_real']:6.2f} {s['bias_rate']:6.2f} {s['p_target']:5.2f} "
            f"{s['theoretical_rate']:10.3f} {s['observed_rate_mean']:10.3f} {s['observed_rate_median']:10.3f}"
        )

    with open(out_dir / "summary_table.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["alpha_real", "bias_rate", "p_target", "theoretical_rate",
                    "observed_rate_mean_W1", "observed_rate_median_W1"])
        for s in summary:
            w.writerow([s["alpha_real"], s["bias_rate"], s["p_target"], s["theoretical_rate"],
                        s["observed_rate_mean"], s["observed_rate_median"]])
    log("Saved summary_table.csv")

    with open(out_dir / "all_results.json", "w", encoding="utf-8") as f:
        json.dump([{k: _make_json_serializable(v) for k, v in r.items()} for r in all_results], f, indent=2)
    log(f"Saved results JSON to {out_dir/'all_results.json'}")
